version: '3'

services:
  db:
    image: 'postgres:12'
    container_name: 'cablecash-db'
    environment:
      - 'POSTGRES_DB=CableCashDB'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - 'cablecash-data:/var/lib/postgresql/data'
    ports:
      - '5456:5432'

  test:
    image: 'postgres:12'
    container_name: 'cablecash-db-test'
    environment:
      - 'POSTGRES_DB=CableCashDB'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    ports:
      - '5455:5432'

  app:
    build: .
    container_name: 'cablecash-api'
    depends_on:
      - 'db'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5456/CableCashDB'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
    ports:
      - "8080:8080"

volumes:
  cablecash-data: